# Generated by Django 4.0.2 on 2023-08-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
