# Generated by Django 4.0.2 on 2023-08-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='product/pdfs', verbose_name='Product_PDF'),
        ),
    ]
